apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snow-terraform-agent.fullname" . }}-secrets
  labels:
    {{- include "snow-terraform-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  AZURE_CLIENT_SECRET: {{ .Values.azure.clientSecret | quote }}
  SERVICENOW_PASSWORD: {{ .Values.serviceNow.password | quote }}
  GITHUB_PERSONAL_ACCESS_TOKEN: {{ .Values.github.personalAccessToken | quote }}
  AZURE_OPENAI_API_KEY: {{ .Values.azureOpenAI.apiKey | quote }}
