apiVersion: v1
kind: Service
metadata:
  name: {{ include "snow-terraform-agent.fullname" . }}
  labels:
    {{- include "snow-terraform-agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "snow-terraform-agent.selectorLabels" . | nindent 4 }}
    role: api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
